[redis]
server = 'localhost'
port = 6379

[sql]
server = 'vde'

[mongodb]
server = 'mongodb+srv://mongo-ptf:'
password = 'NPbVuaH4whukIWC5'
cluster = '@cluster0.hhlpnp3.mongodb.net/?retryWrites=true&w=majority'